# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import file_changelog.file_restore.file_restore_pb2 as file__restore__pb2


class FileRestoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Restore = channel.unary_unary(
                '/file_changelog.FileRestore/Restore',
                request_serializer=file__restore__pb2.RestoreRequest.SerializeToString,
                response_deserializer=file__restore__pb2.RestoreResponse.FromString,
                )


class FileRestoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Restore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileRestoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Restore': grpc.unary_unary_rpc_method_handler(
                    servicer.Restore,
                    request_deserializer=file__restore__pb2.RestoreRequest.FromString,
                    response_serializer=file__restore__pb2.RestoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'file_changelog.FileRestore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileRestore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Restore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/file_changelog.FileRestore/Restore',
            file__restore__pb2.RestoreRequest.SerializeToString,
            file__restore__pb2.RestoreResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
