# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import faker_generator.faker_pb2 as faker__pb2


class FakerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QuickFake = channel.unary_unary(
                '/faker.Faker/QuickFake',
                request_serializer=faker__pb2.QuickFakeRequest.SerializeToString,
                response_deserializer=faker__pb2.QuickFakeResponse.FromString,
                )
        self.BatchFake = channel.unary_unary(
                '/faker.Faker/BatchFake',
                request_serializer=faker__pb2.BatchFakeRequest.SerializeToString,
                response_deserializer=faker__pb2.BatchFakeResponse.FromString,
                )


class FakerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QuickFake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchFake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FakerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QuickFake': grpc.unary_unary_rpc_method_handler(
                    servicer.QuickFake,
                    request_deserializer=faker__pb2.QuickFakeRequest.FromString,
                    response_serializer=faker__pb2.QuickFakeResponse.SerializeToString,
            ),
            'BatchFake': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchFake,
                    request_deserializer=faker__pb2.BatchFakeRequest.FromString,
                    response_serializer=faker__pb2.BatchFakeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'faker.Faker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Faker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QuickFake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/faker.Faker/QuickFake',
            faker__pb2.QuickFakeRequest.SerializeToString,
            faker__pb2.QuickFakeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchFake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/faker.Faker/BatchFake',
            faker__pb2.BatchFakeRequest.SerializeToString,
            faker__pb2.BatchFakeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
