# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faker.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66\x61ker.proto\x12\x05\x66\x61ker\"4\n\x10QuickFakeRequest\x12\x0e\n\x06locale\x18\x01 \x01(\t\x12\x10\n\x08provider\x18\x02 \x01(\t\"#\n\x11QuickFakeResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\")\n\x0bProviderMap\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"[\n\x10\x42\x61tchFakeRequest\x12\x0e\n\x06locale\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\x12(\n\x0cproviderMaps\x18\x03 \x03(\x0b\x32\x12.faker.ProviderMap\"#\n\x11\x42\x61tchFakeResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\x8b\x01\n\x05\x46\x61ker\x12@\n\tQuickFake\x12\x17.faker.QuickFakeRequest\x1a\x18.faker.QuickFakeResponse\"\x00\x12@\n\tBatchFake\x12\x17.faker.BatchFakeRequest\x1a\x18.faker.BatchFakeResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'faker_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUICKFAKEREQUEST._serialized_start=22
  _QUICKFAKEREQUEST._serialized_end=74
  _QUICKFAKERESPONSE._serialized_start=76
  _QUICKFAKERESPONSE._serialized_end=111
  _PROVIDERMAP._serialized_start=113
  _PROVIDERMAP._serialized_end=154
  _BATCHFAKEREQUEST._serialized_start=156
  _BATCHFAKEREQUEST._serialized_end=247
  _BATCHFAKERESPONSE._serialized_start=249
  _BATCHFAKERESPONSE._serialized_end=284
  _FAKER._serialized_start=287
  _FAKER._serialized_end=426
# @@protoc_insertion_point(module_scope)
