// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.49.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names

import 'dart:convert';
import 'dart:async';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

abstract class Native {
  Future<void> main({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainConstMeta;

  Future<int> getCounter({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetCounterConstMeta;

  Future<int> increment({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kIncrementConstMeta;

  Future<int> decrement({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kDecrementConstMeta;

  Future<int> createStorageDirectory({required String s, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCreateStorageDirectoryConstMeta;

  /// 获取文件hash值
  Future<String> getFileHash({required String filePath, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetFileHashConstMeta;

  /// 根据文件hash值软删除文件
  Future<int> deleteFileByFileHash({required String fileHash, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kDeleteFileByFileHashConstMeta;

  /// 初始化数据库，创建数据库连接池
  Future<void> initMysql({required String confPath, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kInitMysqlConstMeta;

  /// 获取所有状态
  Future<List<TodoStatus>> getStatusTypes({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetStatusTypesConstMeta;

  /// 获取所有todo
  Future<List<TodoDetails>> getTodos({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetTodosConstMeta;

  /// 获取所有文件
  Future<List<FileDetails>> getFiles({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetFilesConstMeta;

  /// 创建文件
  Future<int> newFile({required NativeFileSummary f, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kNewFileConstMeta;
}

class FileDetails {
  final int fileId;
  final String? fileName;
  final String? filePath;
  final int isDeleted;
  final DateTime? createAt;
  final DateTime? updateAt;
  final String? fileHash;
  final int versionControl;

  FileDetails({
    required this.fileId,
    this.fileName,
    this.filePath,
    required this.isDeleted,
    this.createAt,
    this.updateAt,
    this.fileHash,
    required this.versionControl,
  });
}

class NativeFileSummary {
  final String? fileName;
  final String? filePath;
  final String? fileHash;
  final int versionControl;

  NativeFileSummary({
    this.fileName,
    this.filePath,
    this.fileHash,
    required this.versionControl,
  });
}

class TodoDetails {
  final int todoId;
  final String? todoName;
  final String? todoContent;
  final String? todoStatusName;
  final String? todoFrom;
  final String? todoTo;
  final String? taskName;
  final int taskId;
  final String? todoStatusColor;

  TodoDetails({
    required this.todoId,
    this.todoName,
    this.todoContent,
    this.todoStatusName,
    this.todoFrom,
    this.todoTo,
    this.taskName,
    required this.taskId,
    this.todoStatusColor,
  });
}

class TodoStatus {
  final int todoStatusId;
  final String? todoStatusName;
  final String? todoStatusColor;

  TodoStatus({
    required this.todoStatusId,
    this.todoStatusName,
    this.todoStatusColor,
  });
}
