// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.49.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names

import 'dart:convert';
import 'dart:async';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

abstract class Native {
  Future<void> main({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kMainConstMeta;

  Future<int> getCounter({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetCounterConstMeta;

  Future<int> increment({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kIncrementConstMeta;

  Future<int> decrement({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kDecrementConstMeta;

  Future<int> createStorageDirectory({required String s, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kCreateStorageDirectoryConstMeta;

  Future<void> initMysql({required String confPath, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kInitMysqlConstMeta;

  Future<List<String>> getStatusTypes({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetStatusTypesConstMeta;
}
